name: Loader
version: '${version}'
main: com.codenamemc.loader.Main
api-version: '1.20'
folia-supported: true
commands:
  shop:
    description: open shop
  gotohome:
    description: go to home
  loadertutorial:
    description: listen loader tutorial